- hosts: localhost
  name: Main Play
  connection: local

  pre_tasks:
    - name: Update Repositories
      become: true
      ansible.builtin.apt:
        update_cache: true
      changed_when: false
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

    # Update Brew Repositories (if installed)

    - name: Fetch profile
      become: true
      ansible.builtin.include_vars:
        file: ~/.ansible-profile.yml
        name: profile

    - name: Set Variables (MacOS)
      ansible.builtin.set_fact:
        userpath: /Users
        usergroup: staff
      when: ansible_distribution == 'MacOSX'

    - name: Set Variables (Ubuntu)
      ansible.builtin.set_fact:
        userpath: /home
        usergroup: "{{ ansible_user_id }}"
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

  tasks:
    - name: Print current role
      ansible.builtin.debug:
        msg: "our role is {{ profile.role }}"

    # Basic role switch
    - name: Perform base role tasks
      ansible.builtin.include_tasks: "roles/base/main.yml"

    - name: Perform desktop role tasks
      ansible.builtin.include_tasks: "roles/desktop/main.yml"
      when: profile.role == "desktop"

    # end of run cleanup and reporting
    - name: Cleanup Package Cache
      become: true
      ansible.builtin.apt:
        autoclean: true
      changed_when: false
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

    - name: Autoremove Orphan Packages
      become: true
      ansible.builtin.apt:
        autoremove: true
        purge: true
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
