- hosts: localhost
  name: Main Play
  connection: local
  become: true

  pre_tasks:
    - name: Update Repositories
      ansible.builtin.apt:
        update_cache: true
      changed_when: false

    - name: Fetch profile
      ansible.builtin.include_vars:
        file: ~/.ansible-profile.yml
        name: profile

  tasks:
    - name: Print current role
      ansible.builtin.debug:
        msg: "our role is {{ profile.role }}"

    - name: Perform base role tasks
      ansible.builtin.include_tasks: "roles/base/main.yaml"
      when: profile.role == "base"

    - name: Copy Wallpaper File
      ansible.builtin.copy:
        src: roles/desktop/files/wallpaper.jpg
        dest: /usr/share/backgrounds/ansible-wallpaper.jpg
        owner: root
        group: root
        mode: 0700


# - name: set wallpaper
#   become_user: "{{ ansible_user_id }}"
#   community.general.dconf:
#     key: "/org/gnome/desktop/background/picture-uri"
#     value: "'file:///usr/share/backgrounds/ansible-wallpaper.jpg'"

# - name: set wallpaper position
#   become_user: "{{ ansible_user_id }}"
#   community.general.dconf:
#     key: "/org/gnome/desktop/background/picture-options"
#     value: "'zoom'"
