- hosts: localhost
  connection: local
  become: true

  vars:
    fruit: apple

  pre_tasks:
    - name: update repositories
      apt:
        update_cache: yes
      changed_when: False

  tasks:
    - name: TEST MESSAGE
      ansible.builtin.debug:
        msg: "our fruit is {{ fruit }}"
        verbosity: 2

    - name: install packages
      package:
        name:
          - zsh

    - name: copy wallpaper file
      copy:
        src: roles/desktop/files/wallpaper.jpg
        dest: /usr/share/backgrounds/ansible-wallpaper.jpg
        owner: root
        group: root

    - name: set wallpaper
      become_user: jpedley
      dconf:
        key: "/org/gnome/desktop/background/picture-uri"
        value: "'file:///usr/share/backgrounds/ansible-wallpaper.jpg'"

    - name: set wallpaper position
      become_user: jpedley
      dconf:
        key: "/org/gnome/desktop/background/picture-options"
        value: "'zoom'"
