- hosts: localhost
  name: Main Play
  connection: local

  pre_tasks:
    - name: Update Repositories
      become: true
      ansible.builtin.apt:
        update_cache: true
      changed_when: false

    - name: Fetch profile
      become: true
      ansible.builtin.include_vars:
        file: ~/.ansible-profile.yml
        name: profile

  tasks:
    - name: Print current role
      ansible.builtin.debug:
        msg: "our role is {{ profile.role }}"

    # Basic role switch
    - name: Perform base role tasks
      ansible.builtin.include_tasks: "roles/base/main.yml"

    - name: Perform desktop role tasks
      ansible.builtin.include_tasks: "roles/desktop/main.yml"
      when: profile.role == "desktop"

    # end of run cleanup and reporting
    - name: Cleanup Package Cache
      become: true
      ansible.builtin.apt:
        autoclean: true
      changed_when: false

    - name: Autoremove Orphan Packages
      become: true
      ansible.builtin.apt:
        autoremove: true
        purge: true
