# Ansible Galaxy Requirements

roles:
  - name: elliotweiser.osx-command-line-tools
  - name: gantsign.oh-my-zsh
  - name: gantsign.visual-studio-code

collections:
  - name: geerlingguy.mac
  - name: community.general
    version: ">=8.6.0"