- name: Install Desktop Packages
  become: true
  ansible.builtin.package:
    state: latest
    name:
      - fonts-powerline
      - gnome-tweaks

- name: Setup FlatPak Support
  become: true
  ansible.builtin.package:
    name: flatpak
    state: present
