# Features:
# - workspaces span displays
# - Taskbar at bottom
# - 2 finger right-click
# - Set gnome-terminal config/background/font choice

- name: Copy Wallpaper File
  become: true
  ansible.builtin.copy:
    src: roles/desktop/files/wallpaper.jpg
    dest: /usr/share/backgrounds/ansible-wallpaper.jpg
    owner: root
    group: root
    mode: 0644

- name: Set wallpaper
  become_user: "{{ ansible_user_id }}"
  community.general.dconf:
    key: "/org/gnome/desktop/background/picture-uri"
    value: "'file:///usr/share/backgrounds/ansible-wallpaper.jpg'"

- name: Set wallpaper position
  become_user: "{{ ansible_user_id }}"
  community.general.dconf:
    key: "/org/gnome/desktop/background/picture-options"
    value: "'zoom'"

- name: Resize taskbar
  become_user: "{{ ansible_user_id }}"
  community.general.dconf:
    key: "/org/gnome/shell/extensions/dash-to-dock/dash-max-icon-size"
    value: "22"

- name: Rlocate taskbar
  become_user: "{{ ansible_user_id }}"
  community.general.dconf:
    key: "/org/gnome/shell/extensions/dash-to-dock/dock-position"
    value: "'BOTTOM'"
