- name: Copy Wallpaper File
  become: true
  ansible.builtin.copy:
    src: roles/desktop/files/wallpaper.jpg
    dest: /usr/share/backgrounds/ansible-wallpaper.jpg
    owner: root
    group: root
    mode: 0644

- name: Set wallpaper
  become_user: "{{ ansible_user_id }}"
  community.general.dconf:
    key: "/org/gnome/desktop/background/picture-uri"
    value: "'file:///usr/share/backgrounds/ansible-wallpaper.jpg'"

- name: Set wallpaper (Dark Mode)
  become_user: "{{ ansible_user_id }}"
  community.general.dconf:
    key: "/org/gnome/desktop/background/picture-uri-dark"
    value: "'file:///usr/share/backgrounds/ansible-wallpaper.jpg'"

- name: Set wallpaper position
  become_user: "{{ ansible_user_id }}"
  community.general.dconf:
    key: "/org/gnome/desktop/background/picture-options"
    value: "'zoom'"

- name: Hide desktop icons
  become_user: "{{ ansible_user_id }}"
  community.general.dconf:
    key: "/org/gnome/desktop/background/show-desktop-icons"
    value: "false"

- name: Resize taskbar
  become_user: "{{ ansible_user_id }}"
  community.general.dconf:
    key: "/org/gnome/shell/extensions/dash-to-dock/dash-max-icon-size"
    value: "22"

- name: Relocate taskbar
  become_user: "{{ ansible_user_id }}"
  community.general.dconf:
    key: "/org/gnome/shell/extensions/dash-to-dock/dock-position"
    value: "'BOTTOM'"

- name: Set dark mode
  become_user: "{{ ansible_user_id }}"
  community.general.dconf:
    key: "/org/gnome/desktop/interface/gtk-theme"
    value: "'Yaru-dark'"

- name: Install fonts to local
  ansible.builtin.copy:
    src: "roles/desktop/files/fonts/"
    dest: "{{ userpath }}/{{ ansible_user_id }}/.local/share/fonts/"
    directory_mode:
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    mode: 0644

- name: Configure GNOME terminal
  ansible.builtin.include_tasks: config/gnome-terminal-config.yml

- name: Workspace fix 1
  become_user: "{{ ansible_user_id }}"
  community.general.dconf:
    key: "/org/gnome/shell/overrides/workspaces-only-on-primary"
    value: "true"

- name: Workspace fix 2
  become_user: "{{ ansible_user_id }}"
  community.general.dconf:
    key: "/org/gnome/mutter/workspaces-only-on-primary"
    value: "false"

- name: Configure GNOME workspaces extension
  ansible.builtin.include_tasks: config/gnome-matrix-workspaces.yml
