- name: Install fonts to local
  ansible.builtin.copy:
    src: "roles/desktop/files/fonts/"
    dest: "{{ userpath }}/{{ ansible_user_id }}/Library/Fonts/"
    directory_mode:
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    mode: 0644

# ~/Library/Application\ Support/iTerm2/DynamicProfiles
