- name: Install fonts to local
  ansible.builtin.copy:
    src: "roles/desktop/files/fonts/"
    dest: "{{ userpath }}/{{ ansible_user_id }}/Library/Fonts/"
    directory_mode:
    owner: "{{ ansible_user_id }}"
    group: "staff"
    mode: 0644

- name: Ensure iTerm Profiles directory is present
  ansible.builtin.file:
    path: "{{ userpath }}/{{ ansible_user_id }}/Library/Application\ Support/iTerm2/DynamicProfiles"
    state: directory
    mode: 0755

- name: Ensure iTerm Scripts directory is present
  ansible.builtin.file:
    path: "{{ userpath }}/{{ ansible_user_id }}/Library/Application\ Support/iTerm2/Scripts/AutoLaunch"
    state: directory
    mode: 0755

- name: Ensure iTerm Profile is present
  ansible.builtin.copy:
    src: "roles/desktop/files/iterm_profile.json"
    dest: "{{ userpath }}/{{ ansible_user_id }}/Library/Application\ Support/iTerm2/DynamicProfiles/iterm_profile.json"
    owner: "{{ ansible_user_id }}"
    group: "staff"
    mode: 0755

- name: Ensure iTerm Script is present
  ansible.builtin.copy:
    src: "roles/desktop/files/iterm_load.py"
    dest: "{{ userpath }}/{{ ansible_user_id }}/Library/Application\ Support/iTerm2/DynamicProfiles/iterm_load.py"
    owner: "{{ ansible_user_id }}"
    group: "staff"
    mode: 0755
