- name: Remove LibreOffice if present
  become: true
  ansible.builtin.apt:
    pkg: libreoffice*
    state: absent
    purge: true
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
