- name: Copy Wallpaper File
  ansible.builtin.copy:
    src: roles/desktop/files/wallpaper.jpg
    dest: /usr/share/backgrounds/ansible-wallpaper.jpg
    owner: root
    group: root
    mode: 0700

# - name: set wallpaper
#   become_user: "{{ ansible_user_id }}"
#   community.general.dconf:
#     key: "/org/gnome/desktop/background/picture-uri"
#     value: "'file:///usr/share/backgrounds/ansible-wallpaper.jpg'"

# - name: set wallpaper position
#   become_user: "{{ ansible_user_id }}"
#   community.general.dconf:
#     key: "/org/gnome/desktop/background/picture-options"
#     value: "'zoom'"
