- ansible.builtin.include_tasks: tasks/packages.yml

# Install Core Tools for Node, Python and Rust
- ansible.builtin.include_tasks: tasks/software/nvm.yml
- ansible.builtin.include_tasks: tasks/software/poetry.yml
# - ansible.builtin.include_tasks: tasks/software/rust.yml

# Personalisation runs last, assuming dependency on packages
- ansible.builtin.include_tasks: tasks/personalisation.yml
