
- name: Parse Gnome Shell version
  ansible.builtin.shell: gnome-shell --version | sed 's/[^0-9.]*\([0-9.]*\).*/\1/'
  register: r_gnome_extension_parse_shell_version
  changed_when: no

- name: Set extension ID and URL as variables
  ansible.builtin.set_fact:
    extension_id: 1485
    gnome_shell_version: "{{ r_gnome_extension_parse_shell_version.stdout }}"

- name: Get Gnome Shell extension info
  ansible.builtin.uri:
    url: https://extensions.gnome.org/extension-info/?pk={{ extension_id }}&shell_version={{ gnome_shell_version }}
    return_content: yes
  register: r_gnome_extension_info

- name: Set extension manifest as json
  ansible.builtin.set_fact:
    gnome_extension_info: "{{ r_gnome_extension_info.json }}"

- name: Check if workspace matrix extension is already installed
  ansible.builtin.stat:
    path: "{{ userpath }}/{{ ansible_user_id }}/.local/share/gnome-shell/extensions/{{ gnome_extension_info.uuid }}/metadata.json"
  register: r_gnome_extensions_check_existing

- name: Create temporary download directory
  ansible.builtin.tempfile:
    state: directory
    suffix: ".gnome_extension_download"
  register: r_gnome_extension_download_dir
  changed_when: no
  when: r_gnome_extensions_check_existing.stat.exists == False

- block:
    - name: Download Gnome Shell extension - {{ gnome_extension_info.name }}
      get_url:
        url: https://extensions.gnome.org{{ gnome_extension_info.download_url }}
        dest: "{{ r_gnome_extension_download_dir.path }}/{{ gnome_extension_info.uuid }}.zip"
      register: r_gnome_extension_download

    - name: Create install directory - {{ gnome_extension_info.name }}
      file:
        path: "{{ userpath }}/{{ ansible_user_id }}/.local/share/gnome-shell/extensions/{{ gnome_extension_info.uuid }}"
        state: directory
        owner: "{{ ansible_user_uid }}"
        group: "{{ ansible_user_gid }}"
        mode: 0775

    - name: Install Gnome Shell extension - {{ gnome_extension_info.name }}
      unarchive:
        src: "{{ r_gnome_extension_download.dest }}"
        dest: "{{ userpath }}/{{ ansible_user_id }}/.local/share/gnome-shell/extensions/{{ gnome_extension_info.uuid }}"
        remote_src: yes

    - name: Enable Gnome Shell extension - {{ gnome_extension_info.name }}
      command: gnome-shell-extension-tool --enable-extension {{ gnome_extension_info.uuid }}
  always:
    - name: Delete temporary download directory
      file:
        path: "{{ r_gnome_extension_download_dir.path }}"
        state: absent
      changed_when: no
  when: r_gnome_extensions_check_existing.stat.exists == False

- name: Enable relevant gnome extensions
  become_user: "{{ ansible_user_id }}"
  community.general.dconf:
    key: "/org/gnome/shell/enabled-extensions"
    value: "['wsmatrix@martin.zurowietz.de', 'screenshot-window-sizer@gnome-shell-extensions.gcampax.github.com', 'ubuntu-appindicators@ubuntu.com']"

# Configure workspaces extension
