- name: Install nvm latest
  git:
    repo: https://github.com/nvm-sh/nvm.git
    dest: "~/.nvm"
    version: "master"

- name: Install Node.js lts
  shell: "~/.nvm/nvm.sh && nvm install --lts"
  register: nvm_install_result
  changed_when: "'is already installed.' not in nvm_install_result.stderr"
