- name: Install nvm latest
  ansible.builtin.git:
    repo: https://github.com/nvm-sh/nvm.git
    dest: "~/.nvm"
    version: "master"

- name: Source nvm (as done in .zshrc) - 1
  ansible.builtin.shell: export NVM_DIR="$HOME/.nvm"

- name: Source nvm (as done in .zshrc) - 2
  ansible.builtin.shell: bash $NVM_DIR/nvm.sh && nvm install --lts
  register: nvm_install_result
  changed_when: "'is already installed.' not in nvm_install_result.stderr"
