- name: Install nvm latest
  ansible.builtin.git:
    repo: https://github.com/nvm-sh/nvm.git
    dest: "{{ userpath }}/{{ ansible_user_id }}/.nvm"
    version: "master"
    recursive: false

- name: Source nvm (as done in .zshrc) and install lts
  ansible.builtin.command: "bash {{ userpath }}/{{ ansible_user_id }}/.nvm/nvm.sh && nvm install --lts"
  register: nvm_install_result
  changed_when: "'is already installed.' not in nvm_install_result.stderr"
