- name: Install nvm latest
  ansible.builtin.git:
    repo: https://github.com/nvm-sh/nvm.git
    dest: "~/.nvm"
    version: "master"

- name: Source nvm
  ansible.builtin.shell: "zsh ~/.nvm/nvm.sh"

- name: Install Node.js lts
  ansible.builtin.shell: "nvm install --lts"
  register: nvm_install_result
  changed_when: "'is already installed.' not in nvm_install_result.stderr"
