- name: Install nvm latest
  git:
    repo: https://github.com/nvm-sh/nvm.git
    dest: "~/.nvm"
    version: "{% if nvm_version=='latest' %}master{% else %}{{ nvm_version }}{% endif %}"

- name: Install Node.js lts
  shell: ". ./nvm.sh && nvm install --lts"
  args:
    chdir: "~/.nvm"
  register: nvm_install_result
  changed_when: "'is already installed.' not in nvm_install_result.stderr"
