- name: Install Pyenv
  ansible.builtin.git:
    repo: "https://github.com/pyenv/pyenv.git"
    dest: {{ userpath }}/{{ ansible_user_id }}/.pyenv
    depth: 1

- name: Install pyenv-virtualenv plugin
  ansible.builtin.git:
    repo: "https://github.com/pyenv/pyenv-virtualenv.git"
    dest: {{ userpath }}/{{ ansible_user_id }}/.pyenv/plugins/pyenv-virtualenv
    depth: 1

- name: Install pipenv for user
  ansible.builtin.pip:
    name: pipenv
    extra_args: --user
