# - name: Install pyenv first
#   ansible.builtin.include_role:
#     name: gantsign.pyenv
#   vars:
#     pyenv_users:
#       - "{{ ansible_user_id }}"
#     # pyenv_path: "/home/{{ ansible_user_id }}/.pyenv"

- name: Clone Pyenv for users
  become: yes
  become_user: "{{ ansible_user_id  }}"
  command: "git clone -c core.autocrlf=input --depth=1 https://github.com/pyenv/pyenv.git ~/.pyenv"
  args:
    creates: "/home/{{ ansible_user_id }}/.pyenv"
  with_items:
    - "{{ ansible_user_id }}"

- name: set permissions of pyenv for users
  become: yes
  file:
    path: "/home/{{ ansible_user_id }}/.pyenv"
    mode: "go-w"
    recurse: yes
  with_items:
    - "{{ ansible_user_id }}"

- name: Install pipenv for user
  ansible.builtin.pip:
    name: pipenv
    extra_args: --user
