- name: Install pyenv first
  ansible.builtin.include_role:
    name: gantsign.pyenv
  vars:
    pyenv_users:
      - "{{ ansible_user_id }}"
    # pyenv_path: "/home/{{ ansible_user_id }}/.pyenv"

- name: Install pipenv for user
  ansible.builtin.pip:
    name: pipenv
    extra_args: --user
