- name: Install KiCad (Ubuntu)
  community.general.flatpak:
    name: org.kicad.KiCad
    method: user
    state: latest
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Install KiCad (MacOS)
  community.general.homebrew_cask:
    name: kicad
    state: present
  when: ansible_distribution == 'MacOSX'
