- name: Install Obsidian (Ubuntu)
  community.general.flatpak:
    name: md.obsidian.Obsidian
    method: user
    state: latest
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Install Obsidian (MacOS)
  community.general.homebrew_cask:
    name: obsidian
    state: present
  when: ansible_distribution == 'MacOSX'
