- name: Install Obsidian (Ubuntu)
  community.general.flatpak:
    name: md.obsidian.Obsidian
    method: user
    state: present
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
