- name: Install Spotify (Ubuntu)
  community.general.flatpak:
    name: com.spotify.Client
    method: user
    state: present
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
