- name: Install STM32CubeIDE (Ubuntu)
  community.general.flatpak:
    name: com.st.STM32CubeIDE
    method: user
    state: present
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Install STM32CubeIDE (MacOS)
    ansible.builtin.fail:
      msg: This software is not available on the target OS!
