- name: Install STM32CubeIDE (Ubuntu)
  community.general.flatpak:
    name: com.st.STM32CubeIDE
    method: user
    state: present
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
