- name: Install Sublime Merge (Ubuntu)
  community.general.flatpak:
    name: com.sublimemerge.App
    method: user
    state: latest
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Install Sublime Merge (MacOS)
  community.general.homebrew_cask:
    name: sublime-merge
    state: present
  when: ansible_distribution == 'MacOSX'
