- name: Install Visual Studio Code
  ansible.builtin.include_role:
    name: gantsign.visual-studio-code
  vars:
    users:
      - username: "{{ ansible_user_id }}"
        visual_studio_code_extensions:
          - cschlosser.doxdocgen
          - esbenp.prettier-vscode
          - hediet.vscode-drawio
          - ms-python.python
          - ms-python.black-formatter
          - ms-vscode.cpptools
          - ms-vscode.hexeditor
          - ms-vscode-remote.remote-containers
          - ms-vscode-remote.remote-ssh
          - rust-lang.rust-analyzer
          - sebastianvelasco.midnight-blue
          - svelte.svelte-vscode
          - vscode-icons-team.vscode-icons
        visual_studio_code_settings_overwrite: true
        visual_studio_code_settings:
          {
            "editor.detectIndentation": false,
            "editor.fontFamily": "'JetBrains Mono', Consolas, 'Courier New', monospace",
            "editor.fontSize": 13,
            "editor.fontLigatures": true,
            "editor.formatOnSave": true,
            "editor.insertSpaces": true,
            "editor.renderWhitespace": "all",
            "editor.rulers": [80],
            "files.insertFinalNewline": true,
            "files.trimTrailingWhitespace": true,
            "git.enabled": false,
            "[python]": {
              "editor.defaultFormatter": "ms-python.black-formatter"
            },
            "[rust]": {
              "editor.defaultFormatter": "rust-lang.rust-analyzer"
            },
            "[svelte]": {
              "editor.defaultFormatter": "svelte.svelte-vscode"
            },
            "[typescript]": {
              "editor.defaultFormatter": "esbenp.prettier-vscode"
            },
            "workbench.colorTheme": "midnight blue",
            "workbench.iconTheme": "vscode-icons",
            "workbench.tree.indent": 16,
            "workbench.tree.renderIndentGuides": "always"
          }

