- name: Wireshark (Ubuntu)
  become: true
  ansible.builtin.package:
    state: latest
    name: wireshark
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Install Wireshark (MacOS)
  community.general.homebrew_cask:
    name: wireshark
    state: present
  when: ansible_distribution == 'MacOSX'
