- name: Wireshark (Ubuntu)
  community.general.flatpak:
    name: org.wireshark.Wireshark
    method: user
    state: present
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Install Wireshark (MacOS)
  community.general.homebrew_cask:
    name: wireshark
    state: present
  when: ansible_distribution == 'MacOSX'
