- name: Wireshark (Ubuntu)
  community.general.flatpak:
    name: org.wireshark.Wireshark
    method: user
    state: present
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
