- name: Install Base Packages
  become: "{{ 'no' if ansible_distribution == 'MacOS' else 'yes' }}"
  ansible.builtin.package:
    state: latest
    name:
      - build-essential
      - cmake
      - curl
      - git
      - htop
      - libssl-dev
      - ranger
      - rsync
      - screen
      - traceroute
      - wget
      - zsh
