- name: Install Base Packages
  become: yes
  ansible.builtin.package:
    state: latest
    name:
      - build-essential
      - cmake
      - curl
      - git
      - htop
      - libssl-dev
      - ranger
      - rsync
      - screen
      - traceroute
      - wget
      - zsh
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Install Base Packages (MacOS)
  ansible.builtin.package:
    state: latest
    name:
      - build-essential
      - cmake
      - curl
      - git
      - htop
      - libssl-dev
      - ranger
      - rsync
      - screen
      - traceroute
      - wget
      - zsh
  when: ansible_distribution == 'MacOS'
