- name: Install Base Packages
  become: true
  ansible.builtin.package:
    state: latest
    name:
      - build-essential
      - cmake
      - curl
      - git
      - python3-dev
      - ranger
      - rsync
      - screen
      - traceroute
      - wget
      - zsh
