- name: Ensure that Homebrew is installed (MacOS)
  ansible.builtin.include_role:
    name: geerlingguy.mac.homebrew
  when: ansible_distribution == 'MacOSX'

- name: Install Base Packages (Ubuntu)
  become: yes
  ansible.builtin.package:
    state: latest
    name:
      - build-essential
      - cmake
      - curl
      - git
      - htop
      - libssl-dev
      - ranger
      - rsync
      - screen
      - traceroute
      - wget
      - zsh
      - python3-dev
      - python3-venv
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Install Base Packages (MacOS)
  ansible.builtin.homebrew:
    state: latest
    name:
      - curl
      - git
      - htop
      - ranger
      - rsync
      - screen
      - tcptraceroute
      - wget
      - python
  when: ansible_distribution == 'MacOSX'
