- name: Install Base Packages
  become: yes
  ansible.builtin.package:
    state: latest
    name:
      - build-essential
      - cmake
      - curl
      - git
      - htop
      - libssl-dev
      - ranger
      - rsync
      - screen
      - traceroute
      - wget
      - zsh
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Install Base Packages (MacOS)
  ansible.builtin.package:
    state: latest
    name:
      - cmake
      - curl
      - git
      - htop
      - ranger
      - rsync
      - screen
      - wget
  when: ansible_distribution == 'MacOSX'

# Install core Desktop packages (no headless MacOS variants)
- name: Install Core MacOS Packages
  community.general.homebrew_cask:
    name: iterm2
    state: present