# Features:
# - Set default shell, config files, etc...

- name: Check if shell is zsh
  ansible.builtin.shell: echo $0
  register: shell_check

- name: Change default shell to zsh
  become: true
  ansible.builtin.shell: chsh -s $(which zsh)
  when: shell_check.stdout != "zsh"

# - name: Install oh my zsh
#   ansible.builtin.include_tasks: software/oh-my-zsh.yml

- name: Install oh-my-zsh
  ansible.builtin.include_role:
    name: gantsign.oh-my-zsh
  vars:
    oh_my_zsh_theme: agnoster
    oh_my_zsh_update_mode: reminder


- name: Copy .zshrc file
  ansible.builtin.copy:
    src: roles/base/files/.zshrc
    dest: "/home/{{ ansible_user_id }}/.zshrc"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    mode: 0664

- name: Hush login
  ansible.builtin.copy:
    content: ""
    dest: "/home/{{ ansible_user_id }}/.hushlogin"
    force: false
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    mode: 0664

# - name: Create .gitconfig based on profile

# - name: Ensure Git/ directory is present
