- name: Set Mac Variables
  ansible.builtin.set_fact:
    userpath: /Users
    usergroup: staff
  when: ansible_distribution == 'MacOSX'
  
- name: Set Linux Variables
  ansible.builtin.set_fact:
    userpath: /home
    usergroup: "{{ ansible_user_id }}"
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Set username as variable
  ansible.builtin.set_fact:
    username: "{{ ansible_user_id }}"

- name: Delete existing .zshrc file
  ansible.builtin.file:
    path: "{{ userpath }}/{{ ansible_user_id }}/.zshrc"
    state: absent

- name: Install oh-my-zsh
  ansible.builtin.include_role:
    name: gantsign.oh-my-zsh
  vars:
    oh_my_zsh_theme: agnoster
    oh_my_zsh_update_mode: reminder
    users:
      - username: "{{ ansible_user_id }}"

- name: Copy .zshrc file
  ansible.builtin.copy:
    src: roles/base/files/.zshrc
    dest: "{{ userpath }}/{{ ansible_user_id }}/.zshrc"
    owner: "{{ ansible_user_id }}"
    group: "{{ usergroup }}"
    mode: 0664

- name: Hush login
  ansible.builtin.copy:
    content: ""
    dest: "{{ userpath }}/{{ ansible_user_id }}/.hushlogin"
    force: false
    owner: "{{ ansible_user_id }}"
    group: "{{ usergroup }}"
    mode: 0664

- name: Create .gitconfig based on profile
  ansible.builtin.template:
    src: roles/base/templates/.gitconfig.j2
    dest: "{{ userpath }}/{{ ansible_user_id }}/.gitconfig"
    mode: 0664

- name: Ensure Git directory is present
  ansible.builtin.file:
    path: "{{ userpath }}/{{ ansible_user_id }}/Git"
    state: directory
    mode: 0755

- name: Generate ssh key pair if not present
  community.crypto.openssh_keypair:
    path: "~/.ssh/id_rsa"
    type: rsa
    size: 4096
    state: present
    force: false

- name: Change user shell to zsh
  become: true
  ansible.builtin.user:
    name: "{{ username }}"
    shell: /bin/zsh
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
