- name: Set username as variable
  ansible.builtin.set_fact:
    username: "{{ ansible_user_id }}"

- name: Delete existing .zshrc file
  ansible.builtin.file:
    path: "/home/{{ ansible_user_id }}/.zshrc"
    state: absent

- name: Check if shell is zsh
  ansible.builtin.shell: echo $0
  register: shell_check

- name: Change default shell to zsh
  become: true
  ansible.builtin.shell: chsh -s $(which zsh)
  when: shell_check.stdout != "zsh"

- name: Change user shell to zsh
  become: true
  ansible.builtin.user:
    name: "{{ username }}"
    shell: /bin/zsh

- name: Install oh-my-zsh
  ansible.builtin.include_role:
    name: gantsign.oh-my-zsh
  vars:
    oh_my_zsh_theme: agnoster
    oh_my_zsh_update_mode: reminder
    users:
      - username: "{{ ansible_user_id }}"

- name: Copy .zshrc file
  ansible.builtin.copy:
    src: roles/base/files/.zshrc
    dest: "/home/{{ ansible_user_id }}/.zshrc"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    mode: 0664

- name: Hush login
  ansible.builtin.copy:
    content: ""
    dest: "/home/{{ ansible_user_id }}/.hushlogin"
    force: false
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    mode: 0664

- name: Create .gitconfig based on profile
  ansible.builtin.template:
    src: roles/base/templates/.gitconfig.j2
    dest: "/home/{{ ansible_user_id }}/.gitconfig"
    mode: 0664

- name: Ensure Git directory is present
  ansible.builtin.file:
    path: /home/{{ ansible_user_id }}/Git
    state: directory
    mode: 0755

- name: Generate ssh key pair if not present
  community.crypto.openssh_keypair:
    path: "~/.ssh/id_rsa"
    type: rsa
    size: 4096
    state: present
    force: false
